#!/usr/bin/env bash
#A Bash script that displays the content of the file /etc/passwd, using the while loop + IFS
while IFS=":" read -r USERNAME PASSWORD uid GID GECOS HDIR CMD;
do
    echo "The user $USERNAME is part of the $GID gang, lives in $HDIR and rides $CMD. $uid's place is protected by the passcode $PASSWORD, more info about the user here: $GECOS"
done < "/etc/passwd"
