#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
count=0
while [ $count -lt 10 ];
do
    if [ $count -eq 8 ];
    then
	echo -e "Best School\nHi"
    else
	echo "Best School"
    fi
    ((count++))
done
