#!/usr/bin/env bash
# Printing 1 to 20 with comments
count=1
while [ $count -le 20 ];
do
    echo "$count"
    case "$count" in
	4)
	    echo "bad luck from Chine"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((count++))
done
