#!/usr/bin/env bash
# Bash script manages manage_my_process
start() {
    ./manage_my_process &
    pgrep -f manage_my_process > /var/run/my_process.pid
    echo "manage_my_process started"
}
stop() {
    pkill -f manage_my_process &
    sudo rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}
restart() {
    sudo kill "$(cat /var/run/my_process.pid)"
    sudo rm /var/run/my_process.pid
    ./manage_my_process &
    pgrep -f manage_my_process > /var/run/my_process.pid
    echo "manage_my_process restarted"
}
if [ $# -lt 1 ] || [ $# -ge 2 ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
else
    case $1 in
	"start")
	    start
	    ;;
	"stop")
	    stop
	    ;;
	"restart")
	    restart
	    ;;
    esac
fi
